/*C.CONSTRUCCIÓN:CREANDO
/*CICLO1:TABLAS*/

--CRUD GRIS
CREATE TABLE Localidades(nombre varchar(15)NOT NULL,prioridad number(1)NOT NULL,numero number(5)NOT NULL,departamento varchar(15)NOT NULL);
--CRUD VERDE
CREATE TABLE Familias(numero number(5)NOT NULL,localidad varchar(15)NOT NULL);
--CRUD NARANJA
CREATE TABLE Personas(codigo number(7)NOT NULL,numero number(5) NOT NULL,nombre varchar2(50)NOT NULL,genero char(1)NOT NULL,talla char(2) NOT NULL,nacimiento date NOT NULL);
CREATE TABLE Adultos(cedula number(12)NOT NULL,codigo number(7) NOT NULL,correo varchar2(40) NOT NULL,telefono varchar(12) NOT NULL);
--CRUD AZUL
CREATE TABLE Asignaciones(numero number(5) NOT NULL,numero number(9) NOT NULL,fecha date NOT NULL,aceptado varchar(5));
CREATE TABLE Detalles(numero number(9) NOT NULL,orden number(4) NOT NULL ,codigo varchar(5) NOT NULL);
CREATE TABLE Vestuarios(cantidad number(4) NOT NULL,talla char(3)NOT NULL,numero number(9) NOT NULL,orden number(4) NOT NULL);
CREATE TABLE Perecederos(cantidad number(4) NOT NULL,vencimiento date NOT NULL,numero number(9) NOT NULL,orden number(4) NOT NULL);
CREATE TABLE Genericos(cantidad number(4) NOT NULL,numero number(9) NOT NULL,orden number(4) NOT NULL);
CREATE TABLE Alojamientos(numero number(9) NOT NULL,personas number(4) not null,inicio date NOT NULL, fin date NOT NULL)
--CRUD ROSA
CREATE TABLE Bienes(codigo varchar(5) NOT NULL,nombre varchar2(30)NOT NULL,tipo char(1) NOT NULL,medida char(2)NOT NULL,unitario number(5) NOT NULL,retirado varchar(5)NOT NULL);
CREATE TABLE Reemplaza(codigo varchar(5)NOT NULL,codigo varchar(5) NOT NULL);

--CRUD MORADO
CREATE TABLE Opiniones(cedula  number(12)NOT NULL,numero NUMBER(5)NOT NULL,codigo varchar(5) NOT NULL,fecha date NOT NULL,opinion char(1) NOT NULL,justificacion varchar(20)NOT NULL);
CREATE TABLE OpinionesGrupales(numero NUMBER(5)NOT NULL,razon varchar2(100),estrellas char(1)NOT NULL);

/*CICLO1:XTABLAS*/
DROP TABLE Localidades;
DROP TABLE Familias;
DROP TABLE Personas;
DROP TABLE Adultos;
DROP TABLE Asignaciones;
DROP TABLE Detalles;
DROP TABLE Bienes;
DROP TABLE Vestuarios;
DROP TABLE Perecederos;
DROP TABLE Genericos;
DROP TABLE Opiniones;
DROP TABLE OpinionesGrupales;

/*D.CONSTRUCCIÓN POBLANDO*/
/*CICLO 1: PoblarOk*/

/*POBLAR CRUD AZUL*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (435896965, 7031, 'OQ280');
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (271875700, 5249, 'HT010');
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192330346, 4164, 'HT061');

/*POBLAR CRUD NARANJA*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (5799119, 15441, 'JUAN DAVID ABADIA', 'M', 'S', '16/4/1971');
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (7859914, 12243, 'NICOLLE SUAREZ', 'F', 'XS', '16/4/1971');
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'DANIEL ALEJANDRO ESCOBAR', 'O', 'L', '15/10/1993');

/*POBLAR CRUD VERDE*/
insert into FAMILIAS (NUMERO) values (15441);
insert into FAMILIAS (NUMERO) values (12243);
insert into FAMILIAS (NUMERO) values (17545);

/*POBLAR CRUD GRIS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, 'CUNDINAMARCA');
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('SUBA', 4, 12243, 'CUNDINAMARCA');
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('USAQUEN', 2, 17545, 'CUNDINAMARCA');

/*POBLAR CRUD PLATEADO*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (182679159861, 48393, 'OQ280', '12/10/2014', 'E', 'FUE BUEN SERVICIO');
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (669008229414, 57694, 'HT010', '30/7/2020', 'B', 'SERVICIO NECESARIO');
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');

/*CICLO 1: PoblarNoOK*/

/*CRUD AZUL*/
/*EL CODIGO SE COMPONE DE SOLO NUMEROS*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (435896965, 7031, '22280');
/*EL CODIGO NO PUEDE SER NULO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values ('NULL', 5249, 'HT016');
/*EL ORDEN ES DE 2 DIGITOS*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192360346, 41, 'HT061');
/*EL NUMEROASIG ES DE 6 DIGITOS*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (330346, 4164, 'HT061');
/*EL CODIGO ES DE 4 Y NO 5 CARACTERES*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192330346, 4164, 'HT06');

/*POBLAR CRUD NARANJA*/
/*EL CODIGO SE COMPONE DE 6 Y NO 7 DIGITOS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (579119, 15441, 'JUAN DAVID ABADIA', 'M', 'S', '16/4/1971');
/*EL NUMEROFAM SE COMPONE DE 4 Y NO 5 */
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (7859914, 12243, 'NICOLLE SUAREZ', 'F', 'XS', '16/4/1971');
/*LA TALLA ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'DANIEL ALEJANDRO ESCOBAR', 'O', 'Z', '15/10/1993');
/*EL GENERO ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'RAUL ANDRES PRIETO', 'X', 'L', '15/10/1983');
/*EL NOMBRE TIENE NUMEROS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'D4V1S C0RT3Z', 'O', 'L', '15/10/1993');

/*POBLAR CRUD VERDE*/
/*EN ESTE CRUD TODOS LOS NUMEROS DEBEN SER DE 5 DIGITOS PERO IGUAL PASAN SI SON DE MENOS DIGITOS*/
insert into FAMILIAS (NUMERO) values (1224);
insert into FAMILIAS (NUMERO) values (175);
insert into FAMILIAS (NUMERO) values (45);
insert into FAMILIAS (NUMERO) values (1);

/*POBLAR CRUD GRIS*/
/*EL DEPARTAMENTO SON LETRAS Y NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '123DFJKSDF');
/*LA PRIORIDAD ES MAYOR A 5*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('SUBA', 7, 12243, 'CUNDINAMARCA');
/*LA LOCALIDAD SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('23456123', 2, 17545, 'CUNDINAMARCA');
/*EL NUMEROFAM ES DE 4 DIGITOS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 1541, 'CUNDINAMARCA');
/*EL DEPARTAMENTO SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '49201');

/*POBLAR CRUD PLATEADO*/
/*LA CEDULA TIENE 5 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (34521, 15073, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL NUMERO TIENE 2 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 12, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL CODIGOBIEN NO TERMINA EN 0 NI EN 1*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT065', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*LA OPINION ES UN CARACTER DESCONOCIDO*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT061', '11/4/2010', 'X', 'PESIMO SERVICIO');
/*EL CODIGOBIEN SON SOLO 4 CARACTERES Y SOLO NUMEROS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, '2561', '11/4/2010', 'M', 'PESIMO SERVICIO');

/*FALTA POBLAR CRUD ROSADO*/

/*CICLO 1: PoblarNoOK*/
/*SERAN LOS CASOS QUE NO PASAN*/
/*CRUD AZUL*/
/*EL NUMEROASIG ES UN CARACTER*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values ('435896965', 7031, 'OQ280');
/*ORDEN ES UN CARACTER*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (271875700, '5249', 'HT011');
/*CODIGOBIEN ES UN NUMERO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192360346, 41, 61);
/*DETALLES ES NULO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values ( NULL , 4164, 'HT061');
/*ORDEN ES NULO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192330346, NULL, 'HT06');

/*POBLAR CRUD NARANJA*/
/*EL CODIGO SE COMPONE DE 6 Y NO 7 DIGITOS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (579119, 15441, 'JUAN DAVID ABADIA', 'M', 'S', '16/4/1971');
/*EL NUMEROFAM SE COMPONE DE 4 Y NO 5 */
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (7859914, 12243, 'NICOLLE SUAREZ', 'F', 'XS', '16/4/1971');
/*LA TALLA ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'DANIEL ALEJANDRO ESCOBAR', 'O', 'Z', '15/10/1993');
/*EL GENERO ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'RAUL ANDRES PRIETO', 'X', 'L', '15/10/1983');
/*EL NOMBRE TIENE NUMEROS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'D4V1S C0RT3Z', 'O', 'L', '15/10/1993');

/*POBLAR CRUD VERDE*/
/*EN ESTE CRUD TODOS LOS NUMEROS DEBEN SER DE 5 DIGITOS PERO IGUAL PASAN SI SON DE MENOS DIGITOS*/
insert into FAMILIAS (NUMERO) values (1224);
insert into FAMILIAS (NUMERO) values (175);
insert into FAMILIAS (NUMERO) values (45);
insert into FAMILIAS (NUMERO) values (1);

/*POBLAR CRUD GRIS*/
/*EL DEPARTAMENTO SON LETRAS Y NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '123DFJKSDF');
/*LA PRIORIDAD ES MAYOR A 5*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('SUBA', 7, 12243, 'CUNDINAMARCA');
/*LA LOCALIDAD SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('23456123', 2, 17545, 'CUNDINAMARCA');
/*EL NUMEROFAM ES DE 4 DIGITOS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 1541, 'CUNDINAMARCA');
/*EL DEPARTAMENTO SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '49201');

/*POBLAR CRUD PLATEADO*/
/*LA CEDULA TIENE 5 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (34521, 15073, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL NUMERO TIENE 2 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 12, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL CODIGOBIEN NO TERMINA EN 0 NI EN 1*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT065', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*LA OPINION ES UN CARACTER DESCONOCIDO*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT061', '11/4/2010', 'X', 'PESIMO SERVICIO');
/*EL CODIGOBIEN SON SOLO 4 CARACTERES Y SOLO NUMEROS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, '2561', '11/4/2010', 'M', 'PESIMO SERVICIO');


/*D.CONSTRUCCIÓN:PROTEGIENDO*/
--CICLO1:ATRIBUTOS

----CRUD GRIS
CREATE TABLE Localidades(nombre varchar(15)NOT NULL,prioridad number(1)NOT NULL,numero number(5)NOT NULL,departamento varchar(15)NOT NULL);
ALTER TABLE Localidades ADD CONSTRAINT CK_Localidades_prioridad CHECK(prioridad >0 and prioridad<6);

--CRUD VERDE
CREATE TABLE Familias(numero number(5)NOT NULL);

----CRUD NARANJA
CREATE TABLE Personas(codigo number(7)NOT NULL,numero number(5) NOT NULL,nombre varchar2(50)NOT NULL,genero char(1)NOT NULL,talla char(2) NOT NULL,nacimiento date NOT NULL);
ALTER TABLE Personas ADD CONSTRAINT CK_Personas_genero CHECK(genero='M' or genero='F' or genero='O');
ALTER TABLE Personas ADD CONSTRAINT CK_Personas_talla CHECK(talla='XS' or talla='S' or talla='M' or talla='L' or talla='XL');

CREATE TABLE Adultos(cedula number(12)NOT NULL,codigo number(7) NOT NULL,correo varchar2(40) NOT NULL,telefono varchar(12) NOT NULL);
ALTER TABLE Adultos ADD CONSTRAINT CK_Adultos_cedula CHECK(cedula>0);
ALTER TABLE Adultos ADD CONSTRAINT CK_Adultos_correo CHECK(correo LIKE '%@anfitrión.dominio');
ALTER TABLE Adultos ADD CONSTRAINT CK_Adultos_telefonos CHECK(telefonos>999999);
----CRUD AZUL
CREATE TABLE Asignaciones(numero number(5) NOT NULL,numero number(9) NOT NULL,fecha date NOT NULL,aceptado varchar(5)NOT NULL);
ALTER TABLE Asignaciones ADD CONSTRAINT CK_Asignaciones_aceptado CHECK(aceptado='TRUE' or aceptado='FALSE');

CREATE TABLE Detalles(numero number(9) NOT NULL,orden number(4) NOT NULL ,codigo varchar(5) NOT NULL);
ALTER TABLE Detalles  ADD CONSTRAINT CK_Detalles_orden CHECK(orden>0);
--CRUD ROSA
CREATE TABLE Bienes(codigo varchar(5) NOT NULL,nombre varchar2(30)NOT NULL,tipo char(1) NOT NULL,medida char(2)NOT NULL,unitario number(5) NOT NULL,retirado varchar(5)NOT NULL);
ALTER TABLE Bienes ADD CONSTRAINT CK_BIENES_codigo CHECK(codigo LIKE 'UPPER_UPPER_NUMBER_0%'OR codigo LIKE 'UPPER_UPPER_NUMBER_1%');
ALTER TABLE Bienes ADD CONSTRAINT CK_BIENES_tipo CHECK(tipo='G' or tipo='P' or tipo='V' or tipo='A');
ALTER TABLE Bienes ADD CONSTRAINT CK_BIENES_unitario CHECK(unitario>=0 and unitario<=99999);
ALTER TABLE Bienes ADD CONSTRAINT CK_BIENES_aceptado CHECK(aceptado='TRUE' or aceptado='FALSE');

CREATE TABLE Vestuarios(cantidad number(4) NOT NULL,talla char(3)NOT NULL,numero number(9) NOT NULL,orden number(4) NOT NULL);
ALTER TABLE Vestuarios ADD CONSTRAINT CK_Vestuarios_cantidad CHECK(cantidad>0 and cantidad<=9999);
ALTER TABLE Vestuarios ADD CONSTRAINT CK_Vestuarios_talla CHECK(talla='XS' or talla='S' or talla='M' or talla='L' or talla='XL');
ALTER TABLE Vestuarios  ADD CONSTRAINT CK_Vestuarios_orden CHECK(orden>0);

CREATE TABLE Perecederos(cantidad number(4) NOT NULL,vencimiento date NOT NULL,numeroAsig number(9) NOT NULL,orden number(4) NOT NULL);
ALTER TABLE Perecederos ADD CONSTRAINT CK_Perecederos_cantidad CHECK(cantidad>0 and cantidad<=9999);
ALTER TABLE Perecederos  ADD CONSTRAINT CK_Perecederos_orden CHECK(orden>0);

CREATE TABLE Genericos(cantidad number(4) NOT NULL,numero number(9) NOT NULL,orden number(4) NOT NULL);
ALTER TABLE Genericos ADD CONSTRAINT CK_Genericos_cantidad CHECK(cantidad>0 and cantidad<=9999);
ALTER TABLE Genericos  ADD CONSTRAINT CK_Genericos_orden CHECK(orden>0);
----CRUD MORADO
CREATE TABLE Opiniones(cedula  number(12)NOT NULL,numero NUMBER(5)NOT NULL,codigo varchar(5) NOT NULL,fecha date NOT NULL,opinion char(1) NOT NULL,justificacion varchar(20)NOT NULL);
ALTER TABLE Opiniones ADD CONSTRAINT CK_Opiniones_opinion CHECK(opinion='E' OR opinion='B' OR opinion='R' OR opinion='M');
ALTER TABLE Opiniones ADD CONSTRAINT CK_Opiniones_codigo CHECK(codigo LIKE 'UPPER_UPPER_NUMBER_0%'OR codigo LIKE 'UPPER_UPPER_NUMBER_1%');

CREATE TABLE OpinionesGrupales(numero NUMBER(5)NOT NULL,razon varchar2(100),estrellas char(1)NOT NULL);
ALTER TABLE OpinionesGrupales ADD CONSTRAINT CK_OpinionesGrupales_estrellas CHECK(estrellas>0 and estrellas<6);

--PK
ALTER TABLE Localidades ADD PRIMARY KEY (nombre);
ALTER TABLE Familias ADD PRIMARY KEY (numero);
ALTER TABLE Personas ADD PRIMARY KEY (codigo);
ALTER TABLE Adultos ADD PRIMARY KEY (cedula);
ALTER TABLE Asignaciones ADD PRIMARY KEY (numero);
ALTER TABLE Detalles ADD CONSTRAINT PK_Detalle PRIMARY KEY (numero,orden);
ALTER TABLE Bienes ADD PRIMARY KEY (codigo);
ALTER TABLE Vestuarios ADD CONSTRAINT PK_Vestuarios PRIMARY KEY (cantidad,talla);
ALTER TABLE Genericos ADD CONSTRAINT PK_Genericos PRIMARY KEY (cantidad,numero,orden);
ALTER TABLE Opiniones ADD PRIMARY KEY (numero);
ALTER TABLE OpinionesGrupales ADD CONSTRAINT PK_OpinionesGrupales PRIMARY KEY (numero,razon,estrellas);

--FK
ALTER TABLE localidades ADD CONSTRAINT FK_localidades FOREIGN KEY (numero) REFERENCES Familias(numero);
ALTER TABLE Personas ADD CONSTRAINT FK_personas FOREIGN KEY (numero) REFERENCES Familias(numero);
ALTER TABLE Personas ADD CONSTRAINT FK_personas_codigo FOREIGN KEY (codigo) REFERENCES Familias(numero);
ALTER TABLE Familias ADD CONSTRAINT FK_Familias_localidad FOREIGN KEY (localidad) REFERENCES Localidades(nombre);
ALTER TABLE Adultos ADD CONSTRAINT FK_adultos FOREIGN KEY (codigo) REFERENCES Personas(codigo);
ALTER TABLE Asignaciones ADD CONSTRAINT FK_asignaciones FOREIGN KEY (numero) REFERENCES Familias(numero);
ALTER TABLE Asignaciones ADD CONSTRAINT FK_Asignaciones_orden FOREIGN KEY (orden) REFERENCES Detalle(orden);
ALTER TABLE Detalles ADD CONSTRAINT FK_detalles FOREIGN KEY (numero) REFERENCES Asignaciones(numero);
ALTER TABLE Detalles ADD CONSTRAINT FK_detalle FOREIGN KEY (codigo) REFERENCES Bienes(codigo);
ALTER TABLE Vestuarios ADD CONSTRAINT FK_vestuarios FOREIGN KEY (numero) REFERENCES Detalles(numero);
ALTER TABLE Vestuarios ADD CONSTRAINT FK_vestuario FOREIGN KEY (orden) REFERENCES Detalles(orden);
ALTER TABLE Genericos ADD CONSTRAINT FK_Genericos FOREIGN KEY (numero) REFERENCES Detalles(numero);
ALTER TABLE Genericos ADD CONSTRAINT FK_Generico FOREIGN KEY (orden) REFERENCES Detalles(orden);
ALTER TABLE Opiniones ADD CONSTRAINT FK_opiniones FOREIGN KEY (cedula) REFERENCES Adultos(cedula);
ALTER TABLE Opiniones ADD CONSTRAINT FK_opinion FOREIGN KEY (codigo) REFERENCES Bien(codigo);
ALTER TABLE OpinionesGrupales ADD CONSTRAINT FK_opinionesGrupales FOREIGN KEY (numero) REFERENCES Opiniones(numero);
ALTER TABLE Reemplaza ADD CONSTRAINT FK_reemplaza_codigo1 FOREIGN KEY (codigo1)REFERENCES Bienes(codigo);
ALTER TABLE Reemplaza ADD CONSTRAINT FK_reemplaza_codigo2 FOREIGN KEY (codigo)REFERENCES Bienes(codigo);

--UK
ALTER TABLE Opiniones ADD UNIQUE (justificacion);

--poblarNoOk

/*SERAN LOS CASOS QUE NO PASAN*/
/*CRUD AZUL*/
/*EL NUMEROASIG ES UN CARACTER*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values ('435896965', 7031, 'OQ280');
/*ORDEN ES UN CARACTER*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (271875700, '5249', 'HT011');
/*CODIGOBIEN ES UN NUMERO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192360346, 41, 61);
/*DETALLES ES NULO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values ( NULL , 4164, 'HT061');
/*ORDEN ES NULO*/
insert into DETALLES (NUMERO, ORDEN, CODIGO) values (192330346, NULL, 'HT06');

/*POBLAR CRUD NARANJA*/
/*EL CODIGO SE COMPONE DE 6 Y NO 7 DIGITOS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (579119, 15441, 'JUAN DAVID ABADIA', 'M', 'S', '16/4/1971');
/*EL NUMEROFAM SE COMPONE DE 4 Y NO 5 */
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (7859914, 12243, 'NICOLLE SUAREZ', 'F', 'XS', '16/4/1971');
/*LA TALLA ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'DANIEL ALEJANDRO ESCOBAR', 'O', 'Z', '15/10/1993');
/*EL GENERO ES UN CARACTER DESCONOCIDO*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'RAUL ANDRES PRIETO', 'X', 'L', '15/10/1983');
/*EL NOMBRE TIENE NUMEROS*/
insert into PERSONAS (CODIGO, NUMERO, NOMBRE, GENERO, TALLA, NACIMIENTO) values (1057459, 17545, 'D4V1S C0RT3Z', 'O', 'L', '15/10/1993');

/*POBLAR CRUD VERDE*/
/*EN ESTE CRUD TODOS LOS NUMEROS DEBEN SER DE 5 DIGITOS PERO IGUAL PASAN SI SON DE MENOS DIGITOS*/
insert into FAMILIAS (NUMERO) values (1224);
insert into FAMILIAS (NUMERO) values (175);
insert into FAMILIAS (NUMERO) values (45);
insert into FAMILIAS (NUMERO) values (1);

/*POBLAR CRUD GRIS*/
/*EL DEPARTAMENTO SON LETRAS Y NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '123DFJKSDF');
/*LA PRIORIDAD ES MAYOR A 5*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('SUBA', 7, 12243, 'CUNDINAMARCA');
/*LA LOCALIDAD SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('23456123', 2, 17545, 'CUNDINAMARCA');
/*EL NUMEROFAM ES DE 4 DIGITOS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 1541, 'CUNDINAMARCA');
/*EL DEPARTAMENTO SON NUMEROS*/
insert into LOCALIDADES (NOMBRE, PRIORIDAD, NUMERO, DEPARTAMENTO) values ('BOSA', 3, 15441, '49201');

/*POBLAR CRUD PLATEADO*/
/*LA CEDULA TIENE 5 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (34521, 15073, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL NUMERO TIENE 2 CIFRAS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 12, 'HT061', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*EL CODIGOBIEN NO TERMINA EN 0 NI EN 1*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT065', '11/4/2010', 'M', 'PESIMO SERVICIO');
/*LA OPINION ES UN CARACTER DESCONOCIDO*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, 'HT061', '11/4/2010', 'X', 'PESIMO SERVICIO');
/*EL CODIGOBIEN SON SOLO 4 CARACTERES Y SOLO NUMEROS*/
insert into OPINIONES (CEDULA, NUMERO, CODIGO, FECHA, OPINION, JUSTIFICACION) values (479702026795, 15073, '2561', '11/4/2010', 'M', 'PESIMO SERVICIO');

/*E.CONSTRUCCIÓN:CONSULTANDO*/--Consultar los bienes más populares del ultimo mes

SELECT nombre,COUNT(tipo) AS POPULARES
FROM Bienes
GROUP BY nombre
ORDER BY POPULARES Desc;


/*CICLO1:<CONSULTAR LA INFORMACIÓN DE LOS BENEFICIARIOS>*/

SELECT nombre,codigo,genero,talla,nacimiento,numero
FROM Personas,Asignaciones
WHERE aceptado='TRUE';


--REGISTRAR OPINIÓN
INSERT INTO Opiniones(CEDULA,NUMERO,CODIGO,FECHA,OPINION,JUSTIFICACION)VALUES(1010247478,12345,22556,'11/4/2010','EXCELENTE SERVICIO',NULL);

--REGISTRAR ASIGNACIÓN
--FECHA
CREATE OR REPLACE TRIGGER fecha
BEFORE INSERT ON Asignaciones
for each row
    BEGIN
        :new.fecha := SYSDATE;
END fecha;
/

--ESTADO

CREATE OR REPLACE TRIGGER aceptado
BEFORE INSERT ON Asignaciones
for each row
    BEGIN
       if numero>10000 THEN
       	:new.aceptado:='TRUE'
       else
	:new.aceptado:='FALSE';
    END IF;
END;

--número de las personas alojamiento
SELECT COUNT(codigo.Personas) AS cantFam
FROM Personas,Familias
WHERE numero.persona=numero.familia;

ALTER TABLE alojamientos ADD CONSTRAINT CK_alojamientos_numero CHECK(personas<=cantFam);

--La talla del vestuario asignado debe corresponder a la talla de uno de los miembros de la
familia

SELECT talla.vestuario
FROM Vestuarios
WHERE EXISTS (talla.vestuario=talla.persona);