CREATE OR REPLACE TRIGGER Envios_ad
BEFORE INSERT OF numero ON envios

DECLARE 
CINSECUTIVO NUMBER;
Begin
    SLECT MAX(numero) ONTO CONSECUTIVO FROM Envios;
    
    IF(CONSECUTIVO IS NULL)
        :NEW.NUMERO :=1
    ELSE
        :NEW.NUMERO := CONSECUTIVO+1
    END
END